version: "3"
services:
  app:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    expose:
      - "3000"
    command: "npm run dev"
    ports:
      - 3000:3000
