version: "3"
services:
  app:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/home/node/app/src
      - ./node_modules:/home/node/app/node_modules
      - ./images:/home/node/app/images
    expose:
      - "5000"
    command: "npm run dev"
    ports:
      - 5000:5000
